version: '3.8'

services:
  postgres_host:
    image: postgres:13.3
    container_name: postgres_host
    env_file:
      - ./.env
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - prj_network
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    user: "501"
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./data/metabase_data:/metabase-data
      - ./data/sqlite_db:/srv/data
    depends_on:
      - postgres_host
    container_name: metabase
    networks:
      - prj_network
networks:
  prj_network:
    driver: bridge